title: The Butler
baseline: Your blogging assistant
description: A ready to use static blog, powered by Cecil.
baseurl: https://kaleemclarkson.netlify.app/
canonicalurl: true
keywords: [Cecil, Static Site Generator, SSG]
author: Arnaud Ligny
language: en
languages:
  - code: en
    locale: en
  - code: fr
    locale: fr_FR
    config:
      baseline: Votre assistant de blog
      description: Un blog statique prêt à l’emploi, propulsé par Cecil.
      taxonomies:
        tags: tag
theme:
  - comingsoon
comingsoon:
  # customize subscribe form
  subscribe:
    placeholder: Enter Email...
    button: Notify me!
social:
  twitter:
    site: TwitterHandle
  github:
    username: Username

pages:
  body:
    highlight:
      enabled: true
    images:
      lazy:
        enabled: true
      resize:
        enabled: true
      responsive:
        enabled: true
      webp:
        enabled: true
      caption:
        enabled: true
assets:
  images:
    optimize:
      enabled: true
    quality: 75
    responsive:
      enabled: true
      responsive:
      widths: [768, 1024]
      sizes:
        default: "(max-width: 608px) 768px, 1024px"
    webp:
      enabled: true
  compile:
  # customize colors
  variables:
    primary: '#69B7FF'
    secondary: '#69C748'
